### ISSUE TITLE
Wide review

### ISSUE THREAD

**Issue by plehegar** [w3c/dxwg#1502]
- [x] Working draft available for wide review: [10 May 2022](https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/)
- [x] Send notifications to groups listed in [Charter coordination section](https://www.w3.org/2020/02/dx-wg-charter.html#coordination): SHACL CG, schema.org for datasets CG, Open Digital Rights Language (ODRL), EU ISA Programme, Research Data Alliance, GO-FAIR, FORCE11, CO-DATA, EPOS
- [x] Self-reviews done ([i18n,](https://github.com/w3c/dxwg/issues/1504) [Security, Privacy](https://github.com/w3c/dxwg/issues/1507),  [Accessibility](https://github.com/w3c/dxwg/issues/1506), [TAG](https://github.com/w3c/dxwg/issues/1515))
- [x] A11y review - see request at https://github.com/w3c/a11y-request/issues/31
- [x] I18n review - see request at https://github.com/w3c/i18n-request/issues/184
- [x] Privacy review - see request at https://github.com/w3cping/privacy-request/issues/90 opened 3 issues, all replied,  ended in adjustments, all marked as source for future requirements
 - [x] Security review -  see request at https://github.com/w3c/security-request/issues/30, DXWG voted [to move forward in the absence of security review,  if something comes up we will move quickly to address it](https://www.w3.org/2023/01/17-dxwg-minutes#r02).
 - [x] TAG review - see request at https://github.com/w3ctag/design-reviews/issues/758

See also [How to do Wide Review](https://www.w3.org/Guide/documentreview/).

**Comment by plehegar** [comment]
Draft published: https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/

**Comment by pchampin** [comment]
A summary of the contacts with the groups in the [Coordindation section from the charter](https://www.w3.org/2022/06/dx-wg-charter.html#coordination) is available here: https://docs.google.com/document/d/1EPQKTLXHlJUTDWqGrK3tRbfLC3mKHjEu_E26veTcC-U/edit
