### ISSUE TITLE
Issues to be addressed for DCAT3 CR

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1509]
This issue is meant to provide a checklist of what must or should be addressed before DCAT3 CR. 

@agbeltran , @davebrowning , @dr-shorthair , @pwin , @riccardoAlbertoni , please add any you see missing.

Updating RDF (required):
- [x] https://github.com/w3c/dxwg/issues/1498
- [x] https://github.com/w3c/dxwg/pull/1508

Comments to be addressed:
- [x] https://github.com/w3c/dxwg/issues/959 - related PRs: https://github.com/w3c/dxwg/pull/1512

Updating spec wrt the scope of DCAT3 & editorial issues (required, but to check with @plehegar if changes can still be done):
- [x] https://github.com/w3c/dxwg/issues/1350- see PR https://github.com/w3c/dxwg/pull/1555
- [x] https://github.com/w3c/dxwg/issues/1349
- [x] https://github.com/w3c/dxwg/issues/1518 - related PRs: https://github.com/w3c/dxwg/pull/1511, PRs: https://github.com/w3c/dxwg/pull/1510 https://github.com/w3c/dxwg/pull/1551
- [x] https://github.com/w3c/dxwg/issues/1519 - related PRs: https://github.com/w3c/dxwg/pull/1510 https://github.com/w3c/dxwg/pull/1556
- [x] Review [Figure 1](https://w3c.github.io/dxwg/dcat/#fig-dcat-all-attributes) - related PRs: https://github.com/w3c/dxwg/pull/1511
- [x] Remove references to issues that will be addressed in the next version of DCAT - related PRs: https://github.com/w3c/dxwg/pull/1511 and https://github.com/w3c/dxwg/pull/1559

Further editorial changes to consider
- [x] [Figure 1](https://w3c.github.io/dxwg/dcat/#fig-dcat-all-attributes) issue:  https://github.com/w3c/dxwg/issues/1557 -related PRs: https://github.com/w3c/dxwg/pull/1558
- [x] https://github.com/w3c/dxwg/issues/1549 - 

Issues with SpecRef:
- [x] https://github.com/w3c/dxwg/issues/1520

To be decided whether to close or move to future work:
- [x] https://github.com/w3c/dxwg/issues/1332 - we decided to move to future work.

Possible inverse properties to be added (to check with @plehegar if changes can still be done):
- [x] https://github.com/w3c/dxwg/issues/1322 - see PR https://github.com/w3c/dxwg/pull/1554

Other issues
- [x] #1502

**Comment by plehegar** [comment]
re #1332 , I think it's fine to make this change without having to restart the wide review.

**Comment by plehegar** [comment]
The other set ("Updating spec wrt the scope of DCAT3 & editorial issues") is totally fine to do as well btw.

**Comment by pchampin** [comment]
Editing the list above according to [the resolution](https://www.w3.org/2023/11/07-dxwg-minutes#r01) taken today
